// layout.tsx (or RootLayout.tsx)
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/layout/header';
import { SiteFooter } from '@/components/navigation/siteFooter';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex flex-col'>
          <Header />
          {/* <Sidebar /> */}
          <div className='px-4 flex flex-1 min-h-screen w-full'>{children}</div>
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}

// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import './globals.css';
// import { ResizableSidebar } from '@/components/ui/sidebar';
// import { AppSidebar } from '@/components/app-sidebar';
// import { TooltipProvider } from '@/components/ui/tooltip';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Resizable Sidebar App',
//   description: 'An app with a resizable sidebar using react-resizable-panels',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang='en'>
//       <body className={inter.className}>
//         <TooltipProvider>
//           <ResizableSidebar defaultSize={20} minSize={10} maxSize={40}>
//             <AppSidebar />
//           </ResizableSidebar>
//         </TooltipProvider>
//         <main className='flex-1 p-6'>{children}</main>
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from 'next';
// import localFont from 'next/font/local';
// import './globals.css';
// import { SidebarLayout, SidebarTrigger } from '@/components/ui/sidebar';
// import { AppSidebar } from '@/components/app-sidebar';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const { cookies } = await import('next/headers');
//   return (
//     <html lang='en'>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <SidebarLayout
//           defaultOpen={cookies().get('sidebar:state')?.value === 'true'}
//         >
//           <AppSidebar />
//           <main className='flex flex-1 flex-col p-2 transition-all duration-300 ease-in-out'>
//             <div className='h-full rounded-md border-2 border-dashed p-2'>
//               <SidebarTrigger />
//               {children}
//             </div>
//           </main>
//         </SidebarLayout>
//       </body>
//     </html>
//   );
// }
